package utils;

public enum TokenType {
	IDENTYFIER, FLOAT, INT, ASSIGNMENT, REL_OP, MATH_OP, L_PAR, R_PAR, KEYWORD, ASSIGN, DELIM, COMMA, TO,
	STRING, PRINT,
	IF, ELSE, THEN, WHILE, AND, OR, ASSIGN2, INPUT;
}
